[build]
  base    = "selvora-app"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/api/*"
  to     = "https://api.profittracker.carltechs.com/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/auth/*"
  to     = "https://api.profittracker.carltechs.com/auth/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/health"
  to     = "https://api.profittracker.carltechs.com/health"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
